# Generated by Django 5.0.6 on 2025-03-21 06:52

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='C2Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Facility')),
            ],
        ),
        migrations.CreateModel(
            name='C2Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('standard_image', models.ImageField(upload_to='img/standard_images/')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c2.c2facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='C2User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('AM', 'AM'), ('EMP', 'EMP'), ('EV', 'EV')], default='EMP', max_length=20, verbose_name='Position')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sbu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sbu')),
            ],
        ),
        migrations.CreateModel(
            name='C2RecentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('remarks', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('re_schedule', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recent_image', models.ImageField(upload_to='img/recent_images/')),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('remark_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('s_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c2.c2standard')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c2.c2user')),
            ],
            options={
                'ordering': ['-updated'],
                'abstract': False,
            },
        ),
    ]
