# Generated by Django 5.0.6 on 2025-10-01 13:18

import c2.models
import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='C2Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Facility')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=c2.models.upload_to_qrcodes)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='C2TechActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Activity')),
                ('location', models.CharField(max_length=100)),
                ('remarks', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='C2Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('standard_image', models.ImageField(upload_to=c2.models.standard_image_upload_path)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standards', to='c2.c2facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='C2TechActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=c2.models.upload_to_technical)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='c2.c2techactivities')),
            ],
        ),
        migrations.CreateModel(
            name='C2User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('AM', 'AM'), ('EMP', 'EMP'), ('EV', 'EV')], default='EMP', max_length=20, verbose_name='Position')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='c2.c2facility')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('sbu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sbu')),
            ],
        ),
        migrations.AddField(
            model_name='c2techactivities',
            name='remark_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_remarks', to='c2.c2user'),
        ),
        migrations.AddField(
            model_name='c2techactivities',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images_by', to='c2.c2user'),
        ),
        migrations.CreateModel(
            name='C2RecentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('remarks', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('re_schedule', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recent_image', models.ImageField(upload_to=c2.models.recent_image_upload_path)),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('remark_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarked_images', to=settings.AUTH_USER_MODEL)),
                ('s_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='c2.c2standard')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='c2.c2user')),
            ],
            options={
                'ordering': ['-updated'],
                'abstract': False,
            },
        ),
    ]
