# Generated by Django 5.0.6 on 2025-03-22 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='c2recentimage',
            name='remark_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarked_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='c2recentimage',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='c2.c2user'),
        ),
        migrations.AlterField(
            model_name='c2standard',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='c2.c2facility'),
        ),
        migrations.AlterField(
            model_name='c2user',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
