# Generated by Django 5.0.6 on 2025-10-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2techactivityimage',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Image Label/Context'),
        ),
    ]
