# Generated by Django 5.0.6 on 2025-03-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2', '0002_alter_c2recentimage_remark_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2recentimage',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
