# Generated by Django 5.0.6 on 2025-03-22 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2', '0003_c2recentimage_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2user',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='c2.c2facility'),
        ),
    ]
