# Generated by Django 5.0.6 on 2025-03-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2', '0005_remove_c2recentimage_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2facility',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
