# Generated by Django 5.0.6 on 2025-03-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2', '0006_c2facility_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c2recentimage',
            name='recent_image',
            field=models.ImageField(upload_to='recent_image_upload_path'),
        ),
    ]
