# Generated by Django 5.0.6 on 2025-03-25 17:10

import c2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2', '0007_alter_c2recentimage_recent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c2recentimage',
            name='recent_image',
            field=models.ImageField(upload_to=c2.models.recent_image_upload_path),
        ),
    ]
