# Generated by Django 5.0.6 on 2025-03-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2', '0008_alter_c2recentimage_recent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2facility',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='c2facility',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
