# Generated by Django 5.0.6 on 2025-05-15 16:34

import ckeditor.fields
import danao.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanaoFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Facility')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='danao/production/qrcodes/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DanaoStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('standard_image', models.ImageField(upload_to=danao.models.danao_standard_image_upload_path)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standardsDanao', to='danao.danaofacility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DanaoTechActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Activity')),
                ('location', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('remark_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danao_tech_remarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='DanaoTechActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=danao.models.upload_to_technical)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesDanao', to='danao.danaotechactivities')),
            ],
        ),
        migrations.CreateModel(
            name='DanaoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('AM_D', 'AM_D'), ('EMP_D', 'EMP_D'), ('EV_D', 'EV_D')], default='EMP', max_length=20, verbose_name='Position')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danao.danaofacility')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usersDanao', to=settings.AUTH_USER_MODEL)),
                ('sbu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sbu')),
            ],
        ),
        migrations.AddField(
            model_name='danaotechactivities',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images_byDanao', to='danao.danaouser'),
        ),
        migrations.CreateModel(
            name='DanaoRecentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('remarks', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('re_schedule', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recent_image', models.ImageField(upload_to=danao.models.danao_recent_image_upload_path)),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('remark_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarked_imagesDanao', to=settings.AUTH_USER_MODEL)),
                ('s_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='danao.danaostandard')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_imagesDanao', to='danao.danaouser')),
            ],
            options={
                'ordering': ['-updated'],
                'abstract': False,
            },
        ),
    ]
