# Generated by Django 5.0.6 on 2025-10-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='danaotechactivityimage',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Image Label/Context'),
        ),
    ]
