# Generated by Django 5.0.6 on 2025-10-01 13:18

import ckeditor.fields
import django.db.models.deletion
import mindanao.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MindanaoFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Facility')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='mindanao/production/qrcodes/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MindanaoTechActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Activity')),
                ('location', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='MindanaoStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('standard_image', models.ImageField(upload_to=mindanao.models.mindanao_standard_image_upload_path)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standardsmindanao', to='mindanao.mindanaofacility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MindanaoTechActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=mindanao.models.upload_to_technical)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesMindanao', to='mindanao.mindanaotechactivities')),
            ],
        ),
        migrations.CreateModel(
            name='MindanaoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('AM_M', 'AM_M'), ('EMP_M', 'EMP_M'), ('EV_M', 'EV_M')], default='EMP_M', max_length=20, verbose_name='Position')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mindanao.mindanaofacility')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usersMindanao', to=settings.AUTH_USER_MODEL)),
                ('sbu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sbu')),
            ],
        ),
        migrations.AddField(
            model_name='mindanaotechactivities',
            name='remark_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mindanao_tech_remarks', to='mindanao.mindanaouser'),
        ),
        migrations.AddField(
            model_name='mindanaotechactivities',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images_byMindanao', to='mindanao.mindanaouser'),
        ),
        migrations.CreateModel(
            name='MindanaoRecentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('remarks', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('re_schedule', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recent_image', models.ImageField(upload_to=mindanao.models.mindanao_recent_image_upload_path)),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('remark_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarked_imagesMindanao', to=settings.AUTH_USER_MODEL)),
                ('s_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mindanao.mindanaostandard')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_imagesMindanao', to='mindanao.mindanaouser')),
            ],
            options={
                'ordering': ['-updated'],
                'abstract': False,
            },
        ),
    ]
